chore: Revert removing rediscluster (#21)
getsentry/sentry#88559
requires some fixes in sentry-redis-tools but running into dependency issues trying to bump the package version.

ERROR: Cannot install -r requirements-dev-frozen.txt (line 167), -r requirements-dev-frozen.txt (line 169), -r requirements-dev-frozen.txt (line 193) and redis==3.4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested redis==3.4.1
    rb 1.10.0 depends on redis!=3.4.0 and >=2.6
    redis-py-cluster 2.1.0 depends on redis<4.0.0 and >=3.0.0
    sentry-redis-tools 0.4.0 depends on redis>=4.0
reverting https://github.com/getsentry/sentry-redis-tools/pull/12/files per @untitaker's suggestion here. I reverted all the changes in that commit since I wasn't sure what is pertinent to the redis>=3.0 -> redis>=4.0 change. Had to manually port the changes, since files had changed for me to be able to open an automatic revert PR.